# Generated by Django 5.1.6 on 2025-03-11 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0019_student_profile_pic_teacher_profile_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='student',
            name='exam_roll',
        ),
    ]
