# Generated by Django 5.1.6 on 2025-03-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0020_remove_student_batch_remove_student_exam_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll',
        ),
    ]
