# Generated by Django 5.1.5 on 2025-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0021_remove_student_roll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obemark',
            name='att',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='co1',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='co2',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='co3',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='co4',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='co5',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='course',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='mark',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='student',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='tt1',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='tt2',
        ),
        migrations.RemoveField(
            model_name='obemark',
            name='tt3',
        ),
        migrations.AddField(
            model_name='obemark',
            name='Assignment1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Assignment2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Mid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Q1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Q2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Q3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Q4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Q5',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='Sem',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
