# Generated by Django 5.1.5 on 2025-03-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0022_remove_obemark_att_remove_obemark_co1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obemark',
            name='co1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='co2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='co3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='co4',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='obemark',
            name='co5',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
