# Generated by Django 5.1.5 on 2025-03-14 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0023_obemark_co1_obemark_co2_obemark_co3_obemark_co4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obemark',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OBEAPP.assigncourse'),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
