# Generated by Django 5.1.5 on 2025-03-14 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0024_obemark_course_alter_obemark_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='obemark',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OBEAPP.assignstudent'),
        ),
    ]
