# Generated by Django 5.1.6 on 2025-03-16 19:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0025_obemark_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obemark',
            name='Assignment1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Assignment2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Mid',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Q1',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Q2',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Q3',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Q4',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Q5',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='obemark',
            name='Sem',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(30)]),
        ),
        migrations.CreateModel(
            name='CO_PO_Matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_code', models.CharField(choices=[('CO1', 'CO1'), ('CO2', 'CO2'), ('CO3', 'CO3'), ('CO4', 'CO4'), ('CO5', 'CO5')], max_length=10)),
                ('po_code', models.CharField(choices=[('PO1', 'PO1'), ('PO2', 'PO2'), ('PO3', 'PO3'), ('PO4', 'PO4'), ('PO5', 'PO5'), ('PO6', 'PO6'), ('PO7', 'PO7'), ('PO8', 'PO8'), ('PO9', 'PO9'), ('PO10', 'PO10'), ('PO11', 'PO11'), ('PO12', 'PO12')], max_length=10)),
                ('strength', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OBEAPP.course')),
            ],
        ),
    ]
