# Generated by Django 5.1.5 on 2025-03-16 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0026_alter_obemark_assignment1_alter_obemark_assignment2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='obemark',
            name='Sem',
        ),
    ]
