# Generated by Django 5.1.5 on 2025-03-16 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OBEAPP', '0027_remove_obemark_sem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObeSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.FloatField(blank=True, null=True)),
                ('co1', models.FloatField(blank=True, null=True)),
                ('co2', models.FloatField(blank=True, null=True)),
                ('co3', models.FloatField(blank=True, null=True)),
                ('co4', models.FloatField(blank=True, null=True)),
                ('co5', models.FloatField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obesem_course', to='OBEAPP.assigncourse')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obesem_student', to='OBEAPP.assignstudent')),
            ],
        ),
    ]
